### ISSUE TITLE
Pattern undetected for medium.com replacement

### ISSUE THREAD

**Issue by MetaApo13** [Raj9039852537/urlChecker-patternchecker-config#8]
Copied the regexp present in /privacyredirector.json and added it to the advanced editor. Clicking on medium.com links does not trigger pattern detection by the app. The replacement link is not shown. 

Example link: https://medium.com/swlh/web-programming-on-android-e3954bb49358
The regexp for medium.com:
`"Medium to Scribe": {
    "regex": "^https?:\\\/\\\/www\\.medium\\.com\\\/(.*)",
    "replacement": "https:\/\/farside.link\/scribe\/$1",
    "enabled": "true"
  },`

**Comment by Raj9039852537** [comment]
Thanks for reporting
Fixed in [Commit](https://github.com/Raj9039852537/urlChecker-patternchecker-config/commit/c9d9a2a5d03c8ae59fcbb1178f79e9607ffd888d)

**Comment by Solomon1732** [comment]
Medium has been allowing subdomains for a while now, in the style of `https://username.medium.com/whatever`. I don't mind opening a pull request with a pattern. I just don't know how to capture the subdomain and move it to, say, `https://scribe.rip/username/whatever`. I guess a pattern would look like `^https:\/\/([^.]+)\.medium.com\/(.*)`? Where`$1` is the subdomain and `$2` the article?

**Comment by Raj9039852537** [comment]
Thanks 

Used already available regex and fixed the replacement string in [Commit](https://github.com/Raj9039852537/urlChecker-patternchecker-config/commit/396ecd35adf22dee4f7be8bfa33f74d78389ca02)

**Comment by Raj9039852537** [comment]
> I guess a pattern would look like `^https:\/\/([^.]+)\.medium.com\/(.*)`? Where`$1` is the subdomain and `$2` the article?
 
This pattern does not have `www` bypass for main domain
